### ISSUE TITLE
Control if "toArray" should be passed to subobjects

### ISSUE THREAD

**Issue by dpauli** [BlackBonjour/to-array#1]
Right now the *toArray()* functionality is also automatically used by sub objects.

It would be nice if I can control whether this functionality should exist or not.

**Comment by BlackBonjour** [comment]
Converting sub objects is now optional. Does this fit your needs?

https://github.com/BlackBonjour/to-array/commit/dbe38e5fce8e8d73de3bd9757dbe23d5eea2b1e1
